### ISSUE TITLE
is possible auto close after show?

### ISSUE THREAD

**Issue by hukjordanjanaq** [Nolence/just_the_tooltip#39]

**Comment by stargazing-dino** [comment]
The default tooltip closes after it is opened. It mimics the behaviour of the default Flutter `Tooltip`. In contrast, if you want to keep the tooltip open after it has shown, you'll need to specify `isModal` to `true` on the JustTheTooltip construction

```dart
JustTheTooltip(
  isModal: false, // fale is the default. This will hide the tooltip after `showDuration`
)
```

**Comment by stargazing-dino** [comment]
Let me know if this answered your question

**Comment by hukjordanjanaq** [comment]
I'm using just_the_tooltip: ^0.0.9+1, but it's not hidind after it shows.
<img width="421" alt="Captura de Pantalla 2021-10-13 a la(s) 22 18 08" src="https://user-images.githubusercontent.com/48919342/137245118-ac56c08a-1c69-44d7-aa83-4a16406bb660.png">



https://user-images.githubusercontent.com/48919342/137245274-8cfdbc0a-541c-4494-afdd-9c43bcb035da.mov

**Comment by hukjordanjanaq** [comment]
It may be because i'm showing it programmatically?

I tested pressing the child for showing the tooltip and it works fine.

**Comment by stargazing-dino** [comment]
Sorry, can't go fully into this rn. Maybe this weekend. I will point out where I think the issue is though.

In this function in a regular tooltip press it handles the tooltip dismissal.
 https://github.com/Nolence/just_the_tooltip/blob/a143964b91642e2a0ac6624b878994a3b138f49f/lib/src/just_the_tooltip.dart#L523

Because a controller _showTooltip never triggers a mouse click event, those `_hideTooltip` functions are never called which then never set a timer for dismissal. I think the correct option would to pass the controller showTooltip a field that defines the behavior of the tooltip after opened.

**Comment by hukjordanjanaq** [comment]
I got it! Thank you so much for answering.

Thank you for this great library too. Have a nice day!

**Comment by stargazing-dino** [comment]
Alright, I finally got to this and added an `autoClose` field to the controller's `showTooltip`.

```dart
controller.showTooltip(immediately: true, autoClose: true);
```

Note, you'll be limited how long it stays open by either your `hoverShowDuration` or your `showDuration`. I forget which ones which.

This update is hidden behind `0.0.10-dev` so you have to opt into it by specifying that exact version in your pubspec.yaml

Let me know if something sucks. I still need at least one or two more tests before I put stable

**Comment by hukjordanjanaq** [comment]
It works fine, it closes automatically. 

Example with showDuration = Duration(milliseconds: 1500)


https://user-images.githubusercontent.com/48919342/138495922-3d4eed5e-0005-4330-98e8-fa186b469098.mov


Thanks yo so much!

**Comment by stargazing-dino** [comment]
😄   Closing

**Comment by knight0zh** [comment]
auto close is not work. When :
`                triggerMode: TooltipTriggerMode.tap,
`
